version: "3.7"

services:
  skychatgpt:
    build: .
    container_name: skychatgpt
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/src/
    ports:
      - 8003:8000
    environment:
      - OPENAI_TOKEN=YOURTOKEN-FOR-https://api.openai.com/v1/completions
      - OPENAI_TEMPERATURE=0.5
      - OPENAI_MAX_TOKENS=100
      - FRONT_URL_CORS=https://localhost:8082,http://localhost:8080
      - WHISPER_MODEL=tiny